### ISSUE TITLE
Getting JSON error when trying to run on local

### ISSUE THREAD

**Issue by sonicx180** [akash-network/console-old#113]
**Describe the bug**
I'm trying to run this repo on my device and I'm getting this on localhost:3005
`{"statusCode":404,"code":"ERR_INVALID_URL","error":"Not Found","message":"Invalid URL"}`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows
 - chrome

**Additional context**

**Comment by anilmurty** [comment]
@kaushik-rishi - could this be related to any changes made to the default route? (I didn't think you had merged any in but wanted to check)

**Comment by kaushik-rishi** [comment]
> @kaushik-rishi - could this be related to any changes made to the default route? (I didn't think you had merged any in but wanted to check)

Let me check once.

I'll recheck the PR that's merged into the deployment templates. I'll get back.

**Comment by kaushik-rishi** [comment]
Figured out the issue.

@sonicx180 - localhost:3000 is where the frontend is hosted, localhost:3005 is the url for the proxy backend/something on the lines of proxy. 

Just go to localhost:3000. things should be running good.

@anilmurty - we can close this issue on resolution. no problem on the code end.

**Comment by anilmurty** [comment]
Thanks for the quick check @kaushik-rishi - closing now. by the way - I also just checked and my instruction video on the readme also asks to use port 3000 @sonicx180 https://github.com/akash-network/console/blob/main/README.md

**Comment by sonicx180** [comment]
Thanks
