### ISSUE TITLE
Unable to Update RPC Nodes

### ISSUE THREAD

**Issue by chainzero** [akash-network/console-old#119]
Issues attempting to edit the RPC node to testnet-02 endpoint and generally issues with RPC endpoint edits (including mainnet use) as follows:

---NOTE - for clarity screenshots of issues encountered are captured in doc via link below
---Mainnet - if the RPC endpoint is updated - it appears to accept but the endpoint is not actually updated.  Possibly could be cosmetic - I.e. the endpoint is actually updating - but at a minimum it is not reflected/updated in the current endpoint displayed in Console > Settings.
---Testnet - if a RPC endpoint update is attempted the initial verification step of the update is successful but when the subsequent Submit button is selected nothing happens.  At this point the dialog box for the RPC endpoint edit remains open and only option is to cancel out of update/dialog box.  And this is definitely not just cosmetic as no change to the RPC endpoint and remains linked to mainnet chain following cancel.  No logs are generated on the Submit attempt that offer any insight into the issue.

https://docs.google.com/document/d/10PC25zFbhHUlK842gINu55G2YuVluHveQAsWE3o9ECc/edit?usp=sharing (edited)

**Comment by anilmurty** [comment]
reference https://github.com/akash-network/console/issues/115
