### ISSUE TITLE
Adding funds to existing deployment doesn't work

### ISSUE THREAD

**Issue by zJuuu** [akash-network/console-old#135]
**Describe the bug**

**To Reproduce**
1. Open the overview of a existing deployment
2. Click on 'Add Funds'
3. Type in a valid Number
4. Click Send
5. See error in console: Query failed with (18): rpc error: code = InvalidArgument desc = invalid owner address: invalid request

**Expected behavior**
Expect to add funds to the deployment

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser Firefox
 - Version 114.0.1 (64-Bit)

**Additional context**
This happens because of the window.reload function in FundDeploymentButton.tsx. https://github.com/akash-network/console/blob/4be92f710844865f2240950be76c6af78213181b/web/src/components/Deployment/FundDeploymentButton.tsx#L53-L60 The function mxFundDeployment returns no Promise that's why it instantly reloads the page and no funds are send.

**Comment by anilmurty** [comment]
Thanks for reporting @zJuuu
