### ISSUE TITLE
Add testnet chain to keplr doesn't work with port

### ISSUE THREAD

**Issue by zJuuu** [akash-network/console-old#140]
**Describe the bug**
If you insert a testnet rpc url including the port in to the rpc endpoint field it will be recognized as a valid rpc node but clicking on "add custom chain for Testnet" will not open keplr.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Change' next to the rpc endpoint
3. Insert a new rpc endpoint url for the testnet including the port i.e.: 'https://rpc.testnet-02.aksh.pw:443'
4. Click on "Add custom Chain for testnet"

**Expected behavior**
Keplr should open to add the  testnet

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser firefox
 - Version 114.0.2

**Comment by jtary** [comment]
Hey @zJuuu,

Wasn't able to reproduce this. One thing that will cause this behaviour is if you already have the custom chain installed. Could you verify that you don't already have a custom chain in keplr for Testnet?

Thanks,

**Comment by zJuuu** [comment]
Hey @jtary, i couldn't reproduce this too. Could be possible i had the custom chain in keplr already.
