### ISSUE TITLE
[OC MVP] UI/UX fixes for SDL editor

### ISSUE THREAD

**Issue by jtary** [akash-network/console-old#16]
**Describe the bug**
Fix various discrepencies between design and implementation on SDL editor page.

ref: https://www.figma.com/file/5Ahxm6mEoupAk6gS7Cafvj/Overclock-Console-UI-REVIEW?node-id=313%3A2223&t=SZuinktOX4YEufIC-4

- [x] add radius to panels and correct drop-shadow
- [ ] fix padding inside of buttons
- [x] missing secondary element groups (background frames)
- [ ] active fields should be red
- [ ] fix padding around buttons and headers (monaco editor)
- [ ] image name should be above group selection

**Comment by anilmurty** [comment]
complete
