### ISSUE TITLE
Replace Console Landing page with something better

### ISSUE THREAD

**Issue by jtary** [akash-network/console-old#18]
**Is your feature request related to a problem? Please describe.**
Replace this with a better page
![Screen Shot 2022-11-09 at 10 30 06 AM](https://user-images.githubusercontent.com/19495789/200912278-cb99393b-e106-41ec-bbb5-6ae775daea1b.png)

**Comment by anilmurty** [comment]
Closing this in favor of: https://github.com/akash-network/console/issues/100
