### ISSUE TITLE
Migrate workloads off of Lumen provider

### ISSUE THREAD

**Issue by jtary** [akash-network/console-old#26]
Current properties that need to be migrated off the Lumen provider:

- [ ] Akash.network Staging
- [ ] Akash.network Prod
- [ ] Ovrclk Website Staging
- [ ] Ovrclk website Prod
- [ ] Greg's blog
- [ ] Console Proxy Staging
- [ ] Console Web Staging

The above properties, with the exception of Greg's blog, are currently deployed with our website-payment wallet.

### Target Provider Requirements:
- Our own managed provider(s) - https://github.com/ovrclk/engineering/wiki/Overclock-Managed-Providers-on-Akash-Network
- Prod properties should include two different deployment targets, with traffic proxied and managed by a Cloudflare LB. This requirement is for ensuring maximum uptime

### Work involved with each property
- Deploy each property+env to it's target provider
  - Enable ovrclk private image repository pulls
  - Create custom ingress for basic auth if needed
     - Enable Cloudflare SSO to replace basic auth (optional, but desired)
- Update workflow files with new DSEQ
- (prod deployments) Create cloudflare LB
   - Add each deployment replica as an origin
- Update DNS (enable proxy)

### Notes
- Console Prod will be provisioned following the above requirements, no migration work needed

**Comment by anilmurty** [comment]
closing since this is overclk specific
