### ISSUE TITLE
Add In-Product Help

### ISSUE THREAD

**Issue by jtary** [akash-network/console-old#30]
SUMMARY:
1. We would like to add in-product DETAILED HELP in THREE PLACES in the Console app. One is after the user clicks on the icon next to the "Get started with a ready template or upload your own SDL" line and the other for when the user clicks the "help" icon at the bottom of the left side bar (the "?")
2. We would also like to add TOOLTIPS in FOUR places in the app

IN-PRODUCT DETAILED HELP IN SIDE BAR
================================

- [ ] FIRST ITEM. Help after "Get started with a ready template or upload your own SDL"
![Screen Shot 2022-10-24 at 1.27.09 PM.png](https://images.zenhubusercontent.com/629e899db9f72267ca286043/48a65bfc-c736-45e1-8d4e-ee27c324cfc0)
Two changes requested here:
1. Add "what is SDL?" label/ icon. Clicking it should pop open a side bar as shown below
![Screen Shot 2022-12-20 at 10 14 10 AM](https://user-images.githubusercontent.com/19495789/208737039-5c30ba86-c8f8-4c51-a329-25649b6b895c.png)

2. Display the following content in the side bar in the format indicated in the design above (ignore the orange comment icon)
======
"SDL stands for “Stack Definition Language” and, as the name suggests, is a way for you (as a user or tenant) to specify what infrastructure stack you need for your application. The SDL file includes compute needs, locations, pricing and other things that help Akash determine the best provider(s) for you to run your application on.

To dig deeper into SDL and it's various sections, read this [documentation](https://docs.akash.network/readme/stack-definition-language) 

To see some samples SDL configurations, check out this [awesome akash repository](https://github.com/ovrclk/awesome-akash). Each directory in the awesome akash repository contains a sample "deploy.yaml" SDL file that deploys a specific application on to akash"!

======

 - [ ] SECOND ITEM: Clicking Help (?) on the left nav bar, should pop open the side bar with the following elements. The topy and hyperlinks are provided below (hyperlinks should open in new tabs)
![Screen Shot 2022-12-20 at 10 18 28 AM](https://user-images.githubusercontent.com/19495789/208737784-b39c75da-c1ce-4cd1-ae7f-afaba5af80a6.png)

Copy for the above design:

"Documentation": "Review detailed documentation" (hyperlink: https://docs.akash.network/guides/deploy)
"Discussion Forum": "View current and past community discussions" (https://github.com/orgs/akash-network/discussions)
"Discord Server": "Join the Discord server and ask any questions" (https://discord.akash.network/)
"Github Repository": "Check out the Akash Network Open Source code bases and community repository" (https://github.com/akash-network)

 - [ ] THIRD ITEM:
Wallet Help (@aktdenis - can you please add link and screenshot to the figma designs for this? I know we worked on them together but I can't seem to locate it)
Two places we will want to guide people: 1) On the top right "Wallet Connected" action and 2) On the "Connect Wallet" button in the deployment configuration screen (once we implement it).
The help for this needs to be a detailed help in the right side nav bar. Text on the right side nav bar should be as follows:
==========
"Deploying workloads on Akash Network requires you to pay in [Akash Token ($AKT)](https://akash.network/token) using a [Keplr Wallet](https://www.keplr.app/).

To use Keplr wallet with Overclock Console, [install the Keplr browser plugin](https://www.keplr.app/download) for your browser.
There are two main ways to fund your Keplr Wallet with AKT: 
1. Purchase them from one of the exchanges listed below:

- [Kucoin](https://www.kucoin.com/)
- [Crypto.com](https://crypto.com/us)
- [Kraken](https://www.kraken.com/)
- [AscendEx](https://ascendex.com/)
- [Gate.io](https://www.gate.io/)
- [Bittrex](https://bittrex.com/)
- [DigiFinex](https://www.digifinex.com/)

2. If you have tokens of other Cosmos chains you can exchange them for AKT using the [Osmosis App](https://app.osmosis.zone/).

For a step-by-step instruction on all that, consult our documentation on topic [here](https://docs.akash.network/tokens-and-wallets)"

===========

TOOL TIP HELP
===========

- [ ] 1. Hover + tooltip after "Configure Services" here
![Screen Shot 2022-12-20 at 10 16 43 AM](https://user-images.githubusercontent.com/19495789/208737416-1b94d32f-c09b-4215-b17c-0c8dec8e90ed.png)

Text: "This is where you can specify various parameters (one per service) that make up your SDL file. The number and name of the services will vary depending on the application/ SDL"

- [ ] 2. Hover + tooltip help after "pricing" here:
![Screen Shot 2022-10-24 at 2.06.53 PM.png](https://images.zenhubusercontent.com/629e899db9f72267ca286043/567efeb4-2ca3-4970-989d-bd63b2fa61ee)
text: "The value you specify here is the maximum you would like to pay for the compute resources you are requesting for this service. uakt allows you to specify an amount that is a fraction of 1AKT"

- [ ] 3. Hover+tooltip text after "Resources" 
![Screen Shot 2022-12-20 at 10 16 58 AM](https://user-images.githubusercontent.com/19495789/208737467-2b16933f-1039-4078-9cff-4e19f863bdf0.png)
Text: "This is where you specify how much CPU, memory and storage you would like to lease from the provider, to host your application."

- [ ] 4. Deployment details screen 
   - Hover tooltip help next to "Update Deployment" with text "This will update a limited set of fields in an existing/ active deployment. Compute resources and placement criteria are not updatable."
   - Hover tooltip help next to "Re-Deploy" with text "This will create a whole new replica of this deployment. The existing deployment will not be touched."

**Comment by anilmurty** [comment]
@aktdenis - couple requests for you:
1. Could you please update the design images in the issue above (the one with the "what is SDL?" help) - specifically, remove that comment and remove the search bar
2. Could you add a screenshot of the design for "THIRD  ITEM" above?

**Comment by iocozmo** [comment]
Hey all

I'm interested in giving this a stab. Are there any requirements for mobile/smaller device responsiveness? Or should I just worry about getting this to work for desktop primarily? 

Thanks!

**Comment by CrystalDime** [comment]
![HelpCenterFOUR](https://user-images.githubusercontent.com/45443045/229648329-5107ad0a-fda7-4ea9-a6d9-18bbf4edc932.png)
![HelpCenterSDL](https://user-images.githubusercontent.com/45443045/229648363-c0c388b0-4ed1-45c2-b547-9223231eef66.png)
![Screenshot 2023-04-03 192116](https://user-images.githubusercontent.com/45443045/229648380-1baaefe9-2e02-4d83-8931-97a5f58411e9.png)

https://user-images.githubusercontent.com/45443045/229648422-87ef13d3-a47b-4fcc-ab57-2ac0e3f3fa5f.mp4


The thing I'm confused about at this point is IN-PRODUCT DETAILED HELP IN SIDE BAR third item. I'm not sure what's supposed to trigger the third help center window.

**Comment by anilmurty** [comment]
hey @CrystalDime - thanks for working on this! 
Re. your question about the 3rd item in the IN-PRODUCT DETAILED HELP section. This is the popup that shows up when you don't have a Keplr wallet installed (open console in a private browser and you'll see it):

![Screenshot 2023-04-03 at 5 42 38 PM](https://user-images.githubusercontent.com/19495789/229657174-de261db2-057b-4bb2-8f34-8f1b73e451cd.png)


And a couple other things:
1. We can remove the search bar (that was a design idea that we can pursue later)
2. I just realized that the copy for the individual items in this image are placeholders so I am adding copy to the description of the issue above
![Screenshot 2023-04-03 at 5 43 28 PM](https://user-images.githubusercontent.com/19495789/229657341-9a29d9ac-0cd5-4def-9265-eb504af3a826.png)

**Comment by anilmurty** [comment]
@CrystalDime - I've added new copy for item 2 of the in-product help section. 
For item 3, we will want to trigger when the user does not have the keplr wallet installed. It should replace the "install keplr" message that shows in the center of the screen. I cleaned up the formatting of the issue a bit -- if that doesn't help, please wait for @aktdenis to add a design wireframe

**Comment by aktdenis** [comment]
> @aktdenis - couple requests for you:
> 
> 1. Could you please update the design images in the issue above (the one with the "what is SDL?" help) - specifically, remove that comment and remove the search bar
> 2. Could you add a screenshot of the design for "THIRD  ITEM" above?

@anilmurty 

Updated design for what's SDL:
<img width="1683" alt="Screenshot 2023-04-04 at 11 20 40" src="https://user-images.githubusercontent.com/116030971/229747327-bbfc9b02-a546-49d1-bb5c-4434b7933d42.png">

And a screenshot for "THIRD ITEM"
<img width="1421" alt="Screenshot 2023-04-04 at 11 22 58" src="https://user-images.githubusercontent.com/116030971/229747892-585310f6-18c4-475d-86e3-1795ac65788f.png">

**Comment by CrystalDime** [comment]
![SceenShotHelp3](https://user-images.githubusercontent.com/45443045/229833294-00f14fc5-c227-4b9a-858d-5cd97c5fe970.png)
![ScreenShotHelp1](https://user-images.githubusercontent.com/45443045/229833305-90afce3a-7ef6-46d7-91d1-bd58007208d3.png)
![ScreenShotHelp2](https://user-images.githubusercontent.com/45443045/229833315-d74f1419-ef30-42b4-9bda-7f7451953164.png)

Removed search bars, added Keplr wallet help center.

**Comment by anilmurty** [comment]
Thanks @aktdenis 

Great work @CrystalDime - did you also add links for each of the items? I think I put most of them in the description but a may have missed a couple like keplr extension (https://chrome.google.com/webstore/detail/keplr/dmkamcknogkgcdfhhbddcghachkejeap), Individual coin exchanges (should be easy to find those) and Akash docs for wallet set up (https://docs.akash.network/tokens-and-wallets)

Once you have those and have tested a deployment (deploy something like tetris, make sure it works and close out deployment) then you are good to raise a PR for review/ merge. If you need $AKT for testing deployment, share your keplr wallet address and I'll send you some

**Comment by anilmurty** [comment]
@aktdenis - one thing I'm wondering is, if we should have a "?" icon next to the "connect wallet" button so that this side bar is accessible always and not just when the wallet is not installed. Thoughts?

**Comment by anilmurty** [comment]
@CrystalDime - Actually, I'll just decide quickly we can move forward. Let's make all help consistent to the "?" - so, for your implementation:
1. Change the "What is SDL" label to the question mark icon
2. Add a question mark icon next to the "Connect Wallet" button (always present, regardless of what state the wallet is in (not installed, installed but not logged in or installed and logged in). Clicking it brings up the side bar for that help
3. Also, any instances of "Overclock Console" or "the Overclock Console" can be changed to "Akash Console". We had initially thought of naming it differently, and the designs are a remnant of that

All other things can remain as they are in your above screenshots. Once that is done, please raise a PR for review

**Comment by CrystalDime** [comment]
Yes, I added the links for each of the items.

My wallet address is cosmos1mp76wwtn8g3n5eunacwhj6t9gg8ec7vh29zn2n

**Comment by anilmurty** [comment]
Thanks @CrystalDime  - Please send akt wallet address - should be something like akash1tf5avu5d4fh...

**Comment by CrystalDime** [comment]
akash1mp76wwtn8g3n5eunacwhj6t9gg8ec7vh8705nf

**Comment by anilmurty** [comment]
@CrystalDime - sent you 20 $AKT - please confirm

**Comment by CrystalDime** [comment]
Yes. I received it.

**Comment by anilmurty** [comment]
Great! - once you confirm a working deployment (Tetris or something basic from the templates is sufficient) with your forked changes, please include a screen recording of it in a PR and we'll review and merge it.
