### ISSUE TITLE
 ports row looks skewed

### ISSUE THREAD

**Issue by jtary** [akash-network/console-old#4]
- Ubuntu 22.04 LTS
- Google Chrome `Version 109.0.5414.74 (Official Build) (64-bit)`

![image](https://user-images.githubusercontent.com/107317698/214960499-bfd650cc-a9be-4681-8217-8e1a18183d58.png)

**Comment by jtary** [comment]
This doesn't seem to be easy to reproduce. I couldn't reproduce it at all, but looking at the CSS I can see how it could be possible, as the labels and fields aren't linked by anything. Dropping the priority for now, since it doesn't seem to the be easy to get to the messed up state.

**Comment by anilmurty** [comment]
I can't repro this either (tried latest chrome and brave on mac) so mocving to post-ga and we'll address if anyone else complains

**Comment by anilmurty** [comment]
closing this for now until someone else reproduces it
