### ISSUE TITLE
Add Template for Kava RPC

### ISSUE THREAD

**Issue by anilmurty** [akash-network/console-old#42]
We'd like to support being able to spin up a Kava RPC node via console. Three things need to happen for this:

- [x] Test out https://github.com/akash-network/cosmos-omnibus/blob/master/kava/deploy.yml and confirm it works (@troian )
- [x] Add JSON template for kava rpc to https://github.com/akash-network/deploy-templates (@anilmurty )
- [x] Add tile for Kava to https://console.akash.network/new-deployment (@jtary ). Will also need an icon for kava (@aktdenis) 
  - Let's put it where Chia is and Chia (and the rest after it) can shift right.

**Comment by anilmurty** [comment]
PR for the second item in the list https://github.com/akash-network/deploy-templates/pull/2

**Comment by anilmurty** [comment]
Re. 1 (@troian ) - I deployed the omnibus image using console (import SDL) and it seems fine: http://vvbb5s95a9a5j4c2qked8i3bjg.ingress.bdl.computer/net_info?

![Screen Shot 2023-02-21 at 10 48 07 AM](https://user-images.githubusercontent.com/19495789/220432770-cc0800ff-fee9-43ea-acc6-4eb5f8ef907c.png)

**Comment by anilmurty** [comment]
icons (from @aktdenis): https://drive.google.com/drive/folders/1v3El7Eut7ZmKpcB8hD8vQiySkN0pGvVo

**Comment by jtary** [comment]
PR for the template https://github.com/akash-network/console/pull/43

**Comment by anilmurty** [comment]
Tested on v0.1.245 on staging and prod and confirmed this works. 

Side note that rpc node does not sync (catching_up remains true and earliest/ latest blocks show 0) but that is not a console issue
