### ISSUE TITLE
All SDLs aren't working after code refactor

### ISSUE THREAD

**Issue by jtary** [akash-network/console-old#5]
**Describe the bug**
Some SDLs are not returning bids in console (while they do in other tools)

**To Reproduce**
1. Attempt deploy of Tetris
2. Repeat same with minesweeper. no bids received

====
Scott Carruthers
  [20 hours ago](https://ovrclk.slack.com/archives/G013GEQ1Y6A/p1674682519434299?thread_ts=1674681872.119959&cid=G013GEQ1Y6A)
[@anil](https://ovrclk.slack.com/team/U03J6616N77)
 
[@Joseph Tary](https://ovrclk.slack.com/team/U02K6J0FDFH)
 - I am not getting manifest send issues and was able to successfully deploy the Memory game via the console.
However I attempted to deploy the Minesweeper SDL prior and was getting no bids.
Overall results:
-Deployment attempt #1 - Minesweeper - no provider bids received
-Deployment attempt #2 - Minesweeper - no provider bids received
-Deployment attempt #3 - Memory game - deployment successful
====

**Comment by anilmurty** [comment]
updating label to post GA because this issue also occurs with cloudmos

**Comment by bmenzalji** [comment]
Any progress this?

**Comment by jtary** [comment]
The issue wasn't due to the console -- but a problem with something else. It's working now. Closing.
