### ISSUE TITLE
Pre-flight check does not check cert validity sometimes

### ISSUE THREAD

**Issue by anilmurty** [akash-network/console-old#50]
**Describe the bug**
Pre-flight check passes cert check even when the cert page says no valid and current cert

**To Reproduce**
1. Remove/ revoke all certs
2. Attempt deploy
3. Check if the pre-flight check passes
4. Deploy and end in manifest send failure because of "bad cert"

**Expected behavior**
pre-flight check should fail

**Comment by jtary** [comment]
Fixed in https://github.com/akash-network/console/pull/55
