### ISSUE TITLE
Make log window the same size as the side panel

### ISSUE THREAD

**Issue by anilmurty** [akash-network/console-old#52]
The log window currently starts out really sim and then expands as logs come in, stopping at a (seemingly) random place about 2/3rd of the heigh of the side panel. 

We should update this so that:
1. The log window is fixed width (does not grow as the logs come in)
2. The size should match the size of the side panel

![Screen Shot 2023-02-23 at 5 37 07 PM](https://user-images.githubusercontent.com/19495789/221070860-bc29a18f-9718-4b32-8b2b-0ae89cc775c8.png)

**Comment by shumakmanohar** [comment]
How to reproduce this?

**Comment by anilmurty** [comment]
You have to deploy something using console (any template is fine) to see logs. I can post a video if you can't figure it out

**Comment by c0deb1ind31** [comment]
hi, require 5ATK for deployment, i had asked on discord no respone.
wallet address:   akash1edu0wuadkn7v2eut23hcshjmrlr09w0hyef7se

**Comment by shumakmanohar** [comment]
could u post a video , on how to do that

**Comment by avikt18** [comment]
@anilmurty I have raise a PR solving this issue.

**Comment by c0deb1ind31** [comment]
Hi @anilmurty,
In above fix, user is not able to scroll logs or able to select option for auto scroll.

I Have raised a PR #88 solving above issue.

**Comment by anilmurty** [comment]
Thanks @c0deb1ind31 - @jtary will review next week
