### ISSUE TITLE
Cert generation is broken

### ISSUE THREAD

**Issue by jtary** [akash-network/console-old#6]
**Describe the bug**
Generating a cert doesn't seem to work consistenty

**To Reproduce**
1. Generate new cert, confirm "current"
2. Refresh page, see banner saying no active cert
3. Also, sometimes cert generation is requiring explicit activation - this should not be necessary

.

**Comment by jtary** [comment]
This should hopefully be fixed by https://github.com/akash-network/console/pull/34

Leaving this open till I can verify

**Comment by boz** [comment]
Anyone had a chance to verify?

**Comment by anilmurty** [comment]
Tested and confirmed in the prod deployed version (0.124) at https://console.akash.network/ - closing this now.
