### ISSUE TITLE
Remove static atoms which rely on RPC

### ISSUE THREAD

**Issue by jtary** [akash-network/console-old#63]
**Describe the bug**
Currently some queried data (such as provider info), is only pulled once when the application starts up. While this data is unlikely to change during the lifetime of the app, it creates problems if the RPC node changes (as will be possible after #7 is complete).

**Expected behavior**
This data should be pulled using react-query on the component that require it, not stored inside an atom.

**Comment by anilmurty** [comment]
Done per @jtary
