### ISSUE TITLE
Button to Generate New Certificates Generates an Infinite Number of Certificates When Not Connected to a Wallet

### ISSUE THREAD

**Issue by jonasgrilleres** [akash-network/console-old#66]
**Describe the bug**
On the settings page, generating new certificates while not connected to any wallet will run indefinitely and generate an excessive number of certificates.

**To Reproduce**

1. Go to 'Settings' page
2. Click on the 'Generate New Certificate' button
3. Click 'Create' in the modal
4. This state will persist indefinitely:
<img width="270" alt="image" src="https://user-images.githubusercontent.com/5982021/224562653-1c161870-13c6-4520-a859-ba8b79b0827f.png">

**Screenshots**
See the error in the console when confirming the generation of certificates in the modal:
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/5982021/224562331-33bd9fb4-0879-4e3d-a466-99116982424a.png">

See hundreds of (possibly unnecessary) certificates created:
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/5982021/224562381-07bf87cb-4098-4bcc-9e8e-46127f957bd9.png">

**Expected behavior**
I would expect the button to be disabled when the wallet is not connected (with a tooltip or an error message explaining why it is disabled):
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/5982021/224562413-3500d84b-7444-42fd-947e-2e06a9d3e4fd.png">

**Additional context**
I propose this solution: https://github.com/akash-network/console/pull/67. I would be happy to receive feedback on how to properly address this issue.

**Comment by anilmurty** [comment]
Thanks for reporting this and for the solution PR @jonasgrilleres -- I haven't run into this myself or seen it reported so it's great that you did - tagging @jtary to review this and the PR. Also setting this to P2 (since we haven't seen other reports of it) for now (can elevate to P1 if we see more reports) and assigning to you (since you've proposed a solution). Hope that's ok.

**Comment by jonasgrilleres** [comment]
PR #67 was merged, closing this issue!
