### ISSUE TITLE
2 strokes on button "+ New Deployment"

### ISSUE THREAD

**Issue by aktdenis** [akash-network/console-old#71]
**Describe the bug**
2 outlines are shown when hovered over button "+ New Deployment". 

**To Reproduce**
1. Go to 'console.akash.network'
2. Hover on button " + New Deployment"

**Expected behavior**
Hover state should have only one stroke - red. without the gray. 

**Screenshots**
<img width="720" alt="Screenshot 2023-03-16 at 12 31 16" src="https://user-images.githubusercontent.com/116030971/225604155-529cdd8f-af53-4592-8b9a-da9d69cfdb39.png">

**Desktop (please complete the following information):**
 - OS: macos monterey 12.2
 - Browser chrome
 - Version Version 110.0.5481.177 .

**Comment by anilmurty** [comment]
@jtary - is this a good-first-issue?

**Comment by masterismail** [comment]
Hello there! I have found a solution for the issue at hand. I would be happy to offer my assistance and collaborate with you on resolving it.

**Comment by anilmurty** [comment]
@masterismail - that would be great. Please submit a PR and we'll review asap and merge (if it looks good). Also feel free to ask questions here

**Comment by shumakmanohar** [comment]
#82
