### ISSUE TITLE
Lease details missing port numbers

### ISSUE THREAD

**Issue by jtary** [akash-network/console-old#8]
**Describe the bug**

**To Reproduce**
1. Deploy an RPC node with Console
2. Check lease details - notice no port numbers listed
3. Repeat same with CLI or Cloudmos

**Expected behavior**
Expect to see port numbers in lease details the way we do with cloudmos and CLI

**Screenshots**

![image](https://user-images.githubusercontent.com/19495789/211376797-b8d10634-a5c9-42eb-bdf9-0ef5ab94f644.png)

**Comment by anilmurty** [comment]
Assigned P1 because we have heard feedback from users about this
