### ISSUE TITLE
Tie Help to Console Docs once ready

### ISSUE THREAD

**Issue by anilmurty** [akash-network/console-old#80]
**Is your feature request related to a problem? Please describe.**
The help from console to https://docs.akash.network/guides/deploy 

**Describe the solution you'd like**
Clicking on the "?" in Console should open the Console section of our docs site (open in new tab)
![Screenshot 2023-03-22 at 2 52 36 PM](https://user-images.githubusercontent.com/19495789/227046988-cce41f29-b3cd-4bdf-8d86-40a275db5caa.png)

**Additional context**
Eventually we will implement better in-product help as outlined in #30 but until then this is a good intermediate term solution

**Comment by anilmurty** [comment]
Link to console docs: https://docs.akash.network/guides/deploy

**Comment by avikt18** [comment]
@anilmurty @jtary please review the PR
