### ISSUE TITLE
Deployment details indicates "no lease because no bids accepted" even though deployment is fine

### ISSUE THREAD

**Issue by anilmurty** [akash-network/console-old#91]
**Describe the bug**
Banner indicating no lease created, likely because no bids accepted  shown even when deployment is good

**To Reproduce**
1. Deploy something
2. Check deploy details

**Expected behavior**
No banner with errors if deployment is good

**Screenshots**
![Screenshot 2023-03-27 at 9 58 31 AM](https://user-images.githubusercontent.com/19495789/228013174-c2e6178d-4577-4444-bcaf-0bae15f0eeda.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Mac OS 13.2.1 (22D68)]
 - Browser [chrome ]
 - Version [111.0.5563.64 (Official Build) (arm64)]

**Comment by yshsaxena** [comment]
Hi @anilmurty can i take this?

**Comment by yshsaxena** [comment]
Hi @anilmurty, In my local system its working, there is no error indicates "no lease because no bids accepted", PFB the Screenshot.

![Screenshot 2023-03-28 234003](https://user-images.githubusercontent.com/45199433/228329972-72bb14db-c42d-4313-bada-34bd0c095485.png)

**Comment by anilmurty** [comment]
hey - thanks for looking into this. Hmmm -- maybe it isn't consistently reproducible. I'll try again and update here when I have a moment. Meanwhile, feel free to comment on another issue you want to work on

**Comment by anilmurty** [comment]
Closing since I haven't been able to repro it. Will reopen if I see it again
