### ISSUE TITLE
Show topology tile (sub-tile) even if there is only one option

### ISSUE THREAD

**Issue by anilmurty** [akash-network/console-old#99]
**Is your feature request related to a problem? Please describe.**
We had decided to now show any sub-tiles for cases where we don't have multiple options (only have one option)

![Screenshot 2023-04-04 at 3 04 47 PM](https://user-images.githubusercontent.com/19495789/229936081-5f24de2b-17e1-4c41-bc60-9f47b6cea0ec.png)
vs:

![Screenshot 2023-04-04 at 3 27 12 PM](https://user-images.githubusercontent.com/19495789/229936311-2f492a7c-3d3b-4249-b591-30bcd8f86b5f.png)

Based on user feedback, we would like to change this, to display whatever tiles are present (even if it is just one). The logo and copy will be governed by what's specified in the metadata files under https://github.com/akash-network/deploy-templates
(here is the one for Cosmos: https://github.com/akash-network/deploy-templates/blob/main/cosmos/metadata.json)

**Describe the solution you'd like**
Update Console to display a tile, even if it is the only one. 
Alignment should be left justified
Should be selected by default

**Comment by iocozmo** [comment]
I'd like to take this on!

**Comment by anilmurty** [comment]
Thanks @mspilimbergo - I've assigned it to you. Please submit PR when ready. fyi @jtary

**Comment by iocozmo** [comment]
Will do - thanks
